//! Web tools backing the `/search` and `/url` commands (Thuki-style).
//!
//! Pure helpers (HTML→text, result parsing, prompt building) are unit-tested;
//! the async `fetch_url`/`search_web` use a local reqwest client. Everything
//! stays on the user's machine — only the explicitly requested URL/search is
//! fetched, and answers are generated by the local LLM.

use crate::error::{Error, Result};
use crate::models::{FetchedPage, SearchResult};

const USER_AGENT: &str =
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

/// Max characters of page text fed to the model (keeps prompts bounded).
pub const MAX_PAGE_CHARS: usize = 12_000;

/// ASCII case-insensitive substring search; `needle` must be lowercase ASCII.
/// Returns a byte index that is always a valid char boundary (needle is ASCII).
fn find_ci(hay: &str, needle: &str) -> Option<usize> {
    let h = hay.as_bytes();
    let n = needle.as_bytes();
    if n.is_empty() || h.len() < n.len() {
        return None;
    }
    'outer: for i in 0..=h.len() - n.len() {
        for (j, &nb) in n.iter().enumerate() {
            if h[i + j].to_ascii_lowercase() != nb {
                continue 'outer;
            }
        }
        return Some(i);
    }
    None
}

/// Strip a tag block (e.g. `<script>...</script>`) from `s`, case-insensitive.
fn strip_block(s: &str, tag: &str) -> String {
    let open = format!("<{tag}");
    let close = format!("</{tag}>");
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    loop {
        match find_ci(rest, &open) {
            Some(start) => {
                out.push_str(&rest[..start]);
                match find_ci(&rest[start..], &close) {
                    Some(end) => rest = &rest[start + end + close.len()..],
                    None => break, // unclosed: drop the rest
                }
            }
            None => {
                out.push_str(rest);
                break;
            }
        }
    }
    out
}

/// Decode a small set of common HTML entities.
fn decode_entities(s: &str) -> String {
    s.replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
        .replace("&#x27;", "'")
        .replace("&nbsp;", " ")
}

/// Convert HTML to readable plain text: drop script/style, strip tags, decode
/// entities, and collapse whitespace.
pub fn html_to_text(html: &str) -> String {
    let no_script = strip_block(html, "script");
    let no_style = strip_block(&no_script, "style");

    // Strip tags, turning block-ish tags into newlines for readability.
    let mut out = String::with_capacity(no_style.len());
    let mut in_tag = false;
    for c in no_style.chars() {
        match c {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => out.push(c),
            _ => {}
        }
    }
    let decoded = decode_entities(&out);

    // Collapse runs of whitespace; keep paragraph breaks.
    let mut text = String::with_capacity(decoded.len());
    let mut last_blank = false;
    for line in decoded.lines() {
        let trimmed = line.split_whitespace().collect::<Vec<_>>().join(" ");
        if trimmed.is_empty() {
            if !last_blank && !text.is_empty() {
                text.push('\n');
            }
            last_blank = true;
        } else {
            text.push_str(&trimmed);
            text.push('\n');
            last_blank = false;
        }
    }
    let text = text.trim().to_string();
    if text.chars().count() > MAX_PAGE_CHARS {
        text.chars().take(MAX_PAGE_CHARS).collect()
    } else {
        text
    }
}

/// Extract the `<title>` text from HTML, if present.
pub fn extract_title(html: &str) -> Option<String> {
    let start = find_ci(html, "<title")?;
    let gt = html[start..].find('>')? + start + 1;
    let end = find_ci(&html[gt..], "</title>")? + gt;
    let title = decode_entities(html[gt..end].trim());
    if title.is_empty() {
        None
    } else {
        Some(title)
    }
}

/// Percent-decode a string (for DuckDuckGo's `uddg` redirect parameter).
pub fn percent_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'%' if i + 2 < bytes.len() => {
                let hex = std::str::from_utf8(&bytes[i + 1..i + 3]).unwrap_or("");
                if let Ok(b) = u8::from_str_radix(hex, 16) {
                    out.push(b);
                    i += 3;
                } else {
                    out.push(bytes[i]);
                    i += 1;
                }
            }
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b => {
                out.push(b);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// Pull the real target URL out of a DuckDuckGo redirect href.
fn unwrap_ddg_url(href: &str) -> String {
    if let Some(idx) = href.find("uddg=") {
        let rest = &href[idx + 5..];
        let enc = rest.split('&').next().unwrap_or(rest);
        return percent_decode(enc);
    }
    if let Some(stripped) = href.strip_prefix("//") {
        return format!("https://{stripped}");
    }
    href.to_string()
}

/// Parse DuckDuckGo "lite" HTML into search results (best-effort, tolerant).
pub fn parse_ddg_lite(html: &str) -> Vec<SearchResult> {
    let mut results = Vec::new();
    // Find anchors with class "result-link".
    let mut search_from = 0;
    while let Some(rel) = html[search_from..].find("class=\"result-link\"") {
        let anchor_start = search_from + rel;
        // Back up to the enclosing <a ...>; find href before the class.
        let a_open = html[..anchor_start].rfind("<a ").unwrap_or(anchor_start);
        let tag_end = match html[a_open..].find('>') {
            Some(e) => a_open + e,
            None => break,
        };
        let tag = &html[a_open..tag_end];
        let href = tag
            .find("href=\"")
            .map(|h| {
                let s = &tag[h + 6..];
                s.split('"').next().unwrap_or("").to_string()
            })
            .unwrap_or_default();
        // Anchor text is between > and </a>
        let text_start = tag_end + 1;
        let text_end = html[text_start..]
            .find("</a>")
            .map(|e| text_start + e)
            .unwrap_or(text_start);
        let title = decode_entities(&strip_tags(&html[text_start..text_end]))
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ");
        if !href.is_empty() && !title.is_empty() {
            results.push(SearchResult {
                title,
                url: unwrap_ddg_url(&href),
                snippet: String::new(),
            });
        }
        search_from = text_end + 4;
    }
    results
}

fn strip_tags(s: &str) -> String {
    let mut out = String::new();
    let mut in_tag = false;
    for c in s.chars() {
        match c {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => out.push(c),
            _ => {}
        }
    }
    out
}

/// Build the prompt for answering from fetched web content with citations.
pub fn build_web_prompt(question: &str, context: &str, sources: &[String]) -> String {
    if context.trim().is_empty() {
        return format!(
            "You are a helpful assistant running locally. Answer the user's question clearly and concisely.\n\nQuestion: {question}\n\nAnswer:"
        );
    }
    let src = if sources.is_empty() {
        String::new()
    } else {
        format!("\nSources:\n- {}\n", sources.join("\n- "))
    };
    format!(
        r#"You are a research assistant. Using ONLY the web content below, answer the question. If the content doesn't cover it, say so. Cite the source URLs you used.
{src}
Web content:
{context}

Question: {question}

Answer:"#,
        src = src,
        context = context,
        question = question,
    )
}

// ---- async networking ---------------------------------------------------

fn client() -> Result<reqwest::Client> {
    reqwest::Client::builder()
        .user_agent(USER_AGENT)
        .timeout(std::time::Duration::from_secs(20))
        .build()
        .map_err(|e| Error::Http(e.to_string()))
}

/// Fetch a URL and reduce it to readable text.
pub async fn fetch_url(url: &str) -> Result<FetchedPage> {
    let url = normalize_url(url);
    let resp = client()?
        .get(&url)
        .send()
        .await
        .map_err(|e| Error::Http(e.to_string()))?;
    if !resp.status().is_success() {
        return Err(Error::Http(format!("{} returned {}", url, resp.status())));
    }
    let html = resp.text().await.map_err(|e| Error::Http(e.to_string()))?;
    let title = extract_title(&html).unwrap_or_else(|| url.clone());
    Ok(FetchedPage {
        url,
        title,
        text: html_to_text(&html),
    })
}

/// Search the web via DuckDuckGo's lite endpoint.
pub async fn search_web(query: &str) -> Result<Vec<SearchResult>> {
    let resp = client()?
        .get("https://lite.duckduckgo.com/lite/")
        .query(&[("q", query)])
        .send()
        .await
        .map_err(|e| Error::Http(e.to_string()))?;
    let html = resp.text().await.map_err(|e| Error::Http(e.to_string()))?;
    Ok(parse_ddg_lite(&html))
}

/// Ensure a URL has a scheme.
pub fn normalize_url(url: &str) -> String {
    let u = url.trim();
    if u.starts_with("http://") || u.starts_with("https://") {
        u.to_string()
    } else {
        format!("https://{u}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn html_to_text_strips_scripts_styles_tags() {
        let html = "<html><head><style>.x{color:red}</style></head><body><h1>Hi</h1><script>alert(1)</script><p>World &amp; more</p></body></html>";
        let text = html_to_text(html);
        assert!(text.contains("Hi"));
        assert!(text.contains("World & more"));
        assert!(!text.contains("alert"));
        assert!(!text.contains("color:red"));
    }

    #[test]
    fn extract_title_works() {
        assert_eq!(
            extract_title("<html><title>My Page</title></html>").as_deref(),
            Some("My Page")
        );
        assert_eq!(extract_title("<html></html>"), None);
    }

    #[test]
    fn percent_decode_handles_encoded_url() {
        assert_eq!(
            percent_decode("https%3A%2F%2Fexample.com%2Fa%20b"),
            "https://example.com/a b"
        );
    }

    #[test]
    fn unwrap_ddg_url_decodes_redirect() {
        let href = "//duckduckgo.com/l/?uddg=https%3A%2F%2Frust-lang.org%2F&rut=abc";
        assert_eq!(unwrap_ddg_url(href), "https://rust-lang.org/");
    }

    #[test]
    fn parse_ddg_lite_extracts_results() {
        let html = r#"<table>
            <tr><td><a class="result-link" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fdoc.rust-lang.org%2Fbook%2F">The Rust Book</a></td></tr>
            <tr><td><a class="result-link" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fcrates.io%2F">crates.io</a></td></tr>
        </table>"#;
        let r = parse_ddg_lite(html);
        assert_eq!(r.len(), 2);
        assert_eq!(r[0].title, "The Rust Book");
        assert_eq!(r[0].url, "https://doc.rust-lang.org/book/");
        assert_eq!(r[1].url, "https://crates.io/");
    }

    #[test]
    fn web_prompt_grounded_vs_general() {
        let general = build_web_prompt("hi", "", &[]);
        assert!(general.contains("Question: hi"));
        assert!(!general.contains("Web content"));

        let grounded = build_web_prompt("what is rust?", "Rust is a language.", &["https://rust-lang.org".into()]);
        assert!(grounded.contains("Web content"));
        assert!(grounded.contains("rust-lang.org"));
        assert!(grounded.contains("Cite the source"));
    }

    #[test]
    fn normalize_url_adds_scheme() {
        assert_eq!(normalize_url("example.com"), "https://example.com");
        assert_eq!(normalize_url("https://x.com"), "https://x.com");
    }
}
